blog/api/urls.py
from django.urls import path
from blog.api import views

app_name = 'blog_api'

urlpatterns = [
    path('list/', views.PostListAPIView.as_view(), name='list'),
    path('<slug:slug>/', views.PostDetailAPIView.as_view(), name='detail'),
    path('<slug:slug>/update/', views.PostUpdateAPIView.as_view(), name='update'),
    path('<slug:slug>/delete/', views.PostDeleteAPIView.as_view(), name='delete'),
    path('post/create/', views.PostCreateAPIView.as_view(), name='create'),
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeeds

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeeds(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('api/', include('blog.api.urls', namespace='blog_api')),

]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils.text import slugify

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):

    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish', blank=True, null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')

    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/api/views.py
from rest_framework.generics import (
        RetrieveUpdateAPIView,
        CreateAPIView,
        ListAPIView,
        RetrieveAPIView,
        DestroyAPIView,
    )

from .serializers import (
        PostListSerializer,
        PostDetailSerializer,
        PostCreateSerializer,

    )

from rest_framework.permissions import (
        AllowAny,
        IsAdminUser,
        IsAuthenticated,


    )

from blog.models import Post
from .permissions import IsOwnerOrReadOnly


class PostCreateAPIView(CreateAPIView):
    queryset = Post.published.all()
    serializer_class = PostCreateSerializer
    permission_classes = [IsAuthenticated, IsAdminUser]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class PostListAPIView(ListAPIView):
    queryset = Post.published.all()
    serializer_class = PostListSerializer
    permission_classes = [AllowAny]


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.published.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.published.all()
    serializer_class = PostCreateSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(aurhor=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.published.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from haystack.query import SearchQuerySet

# Create your views here.


def post_list(request, tag_slug=None):
    posts = Post.published.all()

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts, 3)  # 3 posts in each page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    template = 'blog/post/list.html'
    context = {
        'posts': posts,
        'page': page,
        'tag': tag
    }
    return render(request, template_name=template, context=context)


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, slug=slug,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             )

    # list of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # a comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create a comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the post to the comment
            new_comment.post = post
            # save the comment to the database
            new_comment.save()
            # clear out the comment form
            comment_form = CommentForm()

    else:
        comment_form = CommentForm()

    post_tags_id = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'publish')[:4]

    template = 'blog/post/detail.html'
    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
    }
    return render(request, template_name=template, context=context)


def post_share(request, post_id):
    # retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            name = cd['name']
            email = cd['email']
            to = cd['to']
            comment = cd['comments']
            post_title = post.title
            subject = f'{name} ({email}) recommends you reading "{post_title}"'
            message = f'Read "{post_title}" at {post_url}\n\n{name}\'s comments: {comment}'
            send_mail(subject, message, 'admin@myblog.com', [to])
            sent = True

    else:
        form = EmailPostForm()

    template = 'blog/post/share.html'
    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }
    return render(request, template_name=template, context=context)


def post_search(request):
    form = SearchForm()
    template = 'blog/post/search.html'
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            # count total results
            total_results = results.count()

            context = {'form': form, 'cd': cd, 'results': results, 'total_results': total_results}
            return render(request, template_name=template, context=context)

    return render(request, template_name=template, context={'form': form})

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h2>{{ post.title }}</h2>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|linebreaks }}
    <p><a href="{% url 'blog:post_share' post.id %}">Share this post</a></p>


    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}


    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}


    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|markdown }}
        </div>
    {% empty %}
        <p>There are no comments yet</p>
    {% endfor %}


    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
    My blog
{% endblock %}

{% block content %}

    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>

        <p class="tags">
{#        Tags: {{ post.tags.all|join:", " }}#}
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}

        </p>

        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|truncatewords:30|markdown }}
        <p><a href="{{ post.get_absolute_url }}">Read More</a></p>
        <hr>
    {% endfor %}

{#    for class based list views#}
{#    {% include "blog/snippets/pagination.html" with page=page_obj %}#}

{#    for a function based list view#}
    {% include "blog/snippets/pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block title %}
    Search
{% endblock %}

{% block content %}
    {% if "query" in request.GET %}
        <h2>Search results for "{{ cd.query }}"</h2>
        <h4>Found {{ total_results }} result{{ total_results|pluralize }}</h4>
        {% for result in results %}
            {% with post=result.object %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|truncatewords:5 }}
            {% endwith %}
        {% empty %}
            <p>There are no results matching <b>{{ cd.query }}</b></p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Try again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}
    Share a post
{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Email sent successfully</h1>
        <p>"{{ post.title }}" was successfully share with {{ form.to }}</p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
            <input type="submit" value="Share">
        </form>
    {% endif %}
{% endblock %}